### ISSUE TITLE
Warn/error on unused pipeline option

### ISSUE THREAD

**Issue by russelldj** [Kitware/kwiver#1250]
It happens relatively frequently that I'll try to modify a pipeline and either misspell a config parameter or add the wrong one to an algo. This means setting this parameter fails silently and has caused me quite a few headaches. To the best of my knowledge, there's no mechanism for checking that all config options are used for a given algorithm. It seems like warning when unused params are encountered would be nice, but I certainly understand that this could be a lot of work. 

I'm not necessarily advocating for this, but I think it's worth considering whether the whole config system could be made more programmatic. It seems like this might make this sort of validation easier to do. 

From the developer perspective, I find writing configs rather annoying because there's so much boilerplate. For example, keys are duplicated between the `get_configuration` and `set_configuration` methods and the type in the `config->get_value< type >( key name )` call needs to match the member variable types. Finally, I often have all of my config options set a member variable which is named exactly the same. I think @mattdawkins had a macro that simplified some of these challenges, but I'm not exactly sure.

**Comment by linus-sherrill** [comment]
This is a common problem, but unfortunately, there is no way to automatically config mismatches when the config is loaded due to the dynamic nature of plugin loading.

There is a config diff [class](https://github.com/Kitware/kwiver/blob/master/vital/config/config_difference.h) that provides a way to check a received config against an expected config. The [warn_unspecified_keys()](https://github.com/Kitware/kwiver/blob/78992c7393a2a13a84fed476ac4e8f98dd86d814/vital/config/config_difference.h#L128) method will generate a warning message if one or more expected config items have not been supplied. The [warn_extra_keys()](https://github.com/Kitware/kwiver/blob/78992c7393a2a13a84fed476ac4e8f98dd86d814/vital/config/config_difference.h#L116) method will generate a warning if unexpected config items are supplied. Custom reporting code can be written of these standard approaches are not suitable.

Processes have the same problem with repeated config names and associated types as algorithms. This problem was addresses with a 'traits' approach that binds the name, description, default value, and type together. See [here](https://github.com/Kitware/kwiver/blob/78992c7393a2a13a84fed476ac4e8f98dd86d814/sprokit/processes/trait_utils.h#L91).  Something similar could be done with algorithms. Unfortunately, the way processes and algorithms access their config is slightly different (due to historical reasons) so the process trait interface can not be directly used.

**Comment by linus-sherrill** [comment]
There is also a short writeup on checking the config [here](https://github.com/Kitware/kwiver/blob/master/doc/manuals/arrows/coding_patterns.rst#arrows-coding-patterns). And some usage examples in algorithms (e.g. [here](https://github.com/Kitware/kwiver/blob/78992c7393a2a13a84fed476ac4e8f98dd86d814/arrows/ocv/draw_detected_object_set.cxx#L383)).

**Comment by mleotta** [comment]
@russelldj I think there two separate issues here.  One is config validation at run time and the other is reducing boilerplate when writing configs in algorithms.  There may be some connections between them, but I think they are largely separate.  Regarding the boilerplate, I think we could design a macro-based system such that you only have to specify the name, type, description, and default value of configuration options once in one spot.  This is long overdue, but no one has invested the time into this.  We could probably take inspiration from what @mattdawkins did in vidtk, but from what I remember that would not translate over to KWIVER exactly.  Here is a pattern that could work here, but it's still a bit ugly:

This goes in some shared config header
```c++
#define KWIVER_DECLARE_PARAMS(name, type, default, description) \
  type m_##name {default}

#define KWIVER_GET_CONFIGS(name, type, default, description) \
  config->set_value(#name, m_priv->m_##name, description)

#define KWIVER_SET_CONFIGS(name, type, default, description) \
  m_priv->m_##name = config->get_value<type>(#name, m_priv->m_##name)
```

at the top of your algorithm cxx file you would define parameters like this:
```c++
#define ALGO_PARAMS(func) \
  func(param_name1, double, 1.0, "This is a description of the first parameter"); \
  func(param_name2, bool, false, "This is a description of the second parameter"); \
  func(another_param, std::string, "blah", "Here is yet another parameters")   
```

Then in your private implementation:
```c++
/// Private implementation class
class my_algo::priv
{
public:
  // declare the parameter members
  ALGO_PARAMS(KWIVER_DECLARE_PARAMS);
};
```

Then in you algorithm configuration functions:
```c++
/// Get this algorithm's \link vital::config_block configuration block \endlink
vital::config_block_sptr
my_algo::get_configuration() const
{
  // get base config from base class
  auto config = vital::algo::my_algo::get_configuration();

  // get the configuration parameters with default values
  ALGO_PARAMS(KWIVER_GET_CONFIGS);

  return config;
}

/// Set this algorithm's properties via a config block
void
my_algo::set_configuration(vital::config_block_sptr in_config)
{
  // Starting with our generated vital::config_block to ensure that
  // assumed values are present. An alternative is to check for key
  // presence before performing a get_value() call.
  vital::config_block_sptr config = this->get_configuration();
  config->merge_config(in_config);

  // Set the configuration value from config to member variables of m_priv
  ALGO_PARAMS(KWIVER_SET_CONFIGS);
}
```

**Comment by russelldj** [comment]
Thank you both, this looks really helpful. I'll plan on using the macro solution next time I write a new algo implementation.

**Comment by linus-sherrill** [comment]
One possible improvement would be to use a `c_` as the prefix so it is apparent that the value originated from the config.
As below and elsewhere.

```
#define KWIVER_DECLARE_PARAMS(name, type, default, description) \
  type c_##name {default}

```
